*Instructions*
---------------
Before starting to work, please extract data from data_02.zip to a folder called **data** located at the same level that this notebook.

# 2) Loading and saving data

In [1]:
import pandas as pd

## Loading CSV

First, we need to prepare one csv file to read!

In [2]:
! ls ./data #not working on windows

01_ ACCIDENTES POR TIPO EN  DISTRITOS.xls  T100_SEGMENT_ALL_CARRIER_2015.zip
201712_multas_circulacion_detalle.csv

In [3]:
! unzip ./data/T100_SEGMENT_ALL_CARRIER_2015.zip #not working on windows

Archive:  ./data/T100_SEGMENT_ALL_CARRIER_2015.zip
replace 914310910_T_T100_SEGMENT_ALL_CARRIER_2015_All.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: ^C

In [4]:
! ls -lrt ./

total 156828
-rw-r--r-- 1 dsc dsc     4268 nov  8  2015 914310910_T_T100_SEGMENT_ALL_CARRIER_Terms.csv
-rw-r--r-- 1 dsc dsc     4341 nov  8  2015 914310910_T_T100_SEGMENT_ALL_CARRIER_ReadMe.csv
-rw-r--r-- 1 dsc dsc 51575427 nov  8  2015 914310910_T_T100_SEGMENT_ALL_CARRIER_2015_All.csv
-rwxrwxrwx 1 dsc dsc      515 abr  3 23:31 writeTodayHistory.sh
-rw-r--r-- 1 dsc dsc      627 abr  6 21:46 Class_05v7.py
-rw-r--r-- 1 dsc dsc     2544 abr  6 22:00 05v7_Master_Class.txt
-rw-r--r-- 1 dsc dsc      666 abr  7 12:40 Class_06v7.py
drwxr-xr-x 2 dsc dsc     4096 abr  7 12:48 __pycache__
-rw-r--r-- 1 dsc dsc    51086 abr  7 13:42 Class_06v7.ipynb
-rw-r--r-- 1 dsc dsc     3372 abr  7 13:54 06v7_Master_Class.txt
-rw-r--r-- 1 dsc dsc  8125159 abr 13 17:22 data_02.zip
-rw-r--r-- 1 dsc dsc      912 abr 13 18:07 Class_07v7.ipynb
-rw-r--r-- 1 dsc dsc   456666 abr 13 20:58 01-numpy_pandas_introduction-clean.ipynb
drwxr-xr-x 2 dsc dsc     4096 abr 13 20:59 data
-rw-r--r-- 1 dsc dsc     3262 abr 13 21:21 multas.csv
-rw-r--r-- 1 dsc dsc 11007488 abr 13 21:28 out.xls
-rw-r--r-- 1 dsc dsc  4363924 abr 13 21:28 out.xlsx
-rw-r--r-- 1 dsc dsc 45901761 abr 13 21:28 out.csv
-rw-r--r-- 1 dsc dsc 38543360 abr 13 21:28 example.db
-rw-r--r-- 1 dsc dsc     3262 abr 13 21:29 accidentes.xls
-rw-r--r-- 1 dsc dsc   470208 abr 13 21:53 02-loading_and_saving_data_2018_04_14-clean.ipynb
-rw-r--r-- 1 dsc dsc    14028 abr 14 09:26 03-merge_concatenate_transform-clean.ipynb
-rw-r--r-- 1 dsc dsc      710 abr 14 09:26 Class_08v7.ipynb

In [5]:
#Defining path to CSV file
my_file_path='914310910_T_T100_SEGMENT_ALL_CARRIER_2015_All.csv'

In [6]:
#Reading file and saving in df
df = pd.read_csv(my_file_path)
df.head()

,DEPARTURES_SCHEDULED,DEPARTURES_PERFORMED,PAYLOAD,SEATS,PASSENGERS,FREIGHT,MAIL,DISTANCE,RAMP_TO_RAMP,AIR_TIME,...,AIRCRAFT_GROUP,AIRCRAFT_TYPE,AIRCRAFT_CONFIG,YEAR,QUARTER,MONTH,DISTANCE_GROUP,CLASS,DATA_SOURCE,Unnamed: 50
0,0.0,1.0,528.0,11.0,2.0,0.0,0.0,3899.0,0.0,0.0,...,6,669,1,2015,1,1,8,L,IF,NaN
1,0.0,2.0,3621.0,22.0,2.0,0.0,0.0,2589.0,0.0,0.0,...,6,669,1,2015,1,1,6,L,IF,NaN
2,0.0,1.0,2169.0,11.0,2.0,0.0,0.0,1210.0,0.0,0.0,...,6,669,1,2015,1,1,3,L,DF,NaN
3,0.0,1.0,1342.0,11.0,1.0,0.0,0.0,2316.0,0.0,0.0,...,6,669,1,2015,1,1,5,L,IF,NaN
4,0.0,1.0,275.0,11.0,1.0,0.0,0.0,1023.0,0.0,0.0,...,6,669,1,2015,1,1,3,L,DF,NaN

In [7]:
#df?

In [8]:
#Number of rows on Dataframe
len(df)

146938

Make some operations with the df

In [9]:
df[df['DEPARTURES_PERFORMED'] > 50]['PAYLOAD'].sum()

50535573064.0

In [10]:
%%timeit
df[df['DEPARTURES_PERFORMED'] > 50]['PAYLOAD'].sum()

12.1 ms ± 936 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [11]:
len(df[df['DEPARTURES_PERFORMED'] > 50])

19527

In order to download a file using Python, the use of requests module is recommended

In [12]:
#!wget -o http://datos.madrid.es/egob/catalogo/207831-0-accidentes-trafico.xls

### Example:

In [13]:
import requests
#url="http://datos.madrid.es/egob/catalogo/210104-180-multas-circulacion-detalle.csv"
url = 'http://climatedataapi.worldbank.org/climateweb/rest/v1/country/cru/tas/year/CAN.csv'
response = requests.get(url)
if response.status_code != 200:
    print('Failed to get data:', response.status_code)
else:
    print('First 100 characters of data are')
    print(response.text[:100])

First 100 characters of data are
year,data
1901,-7.67241907119751
1902,-7.862711429595947
1903,-7.910782814025879
1904,-8.15572929382

In [14]:
import requests
my_path="http://datos.madrid.es/egob/catalogo/210104-180-multas-circulacion-detalle.csv"
multas_response = requests.get(my_path)

In [15]:
multas_path = 'multas.csv'
multas_file = open(multas_path, 'wb')
multas_file.write(multas_response.content)
multas_file.close()

In [16]:
! wc -l {multas_path} #unix

1 multas.csv

In [17]:
! head -n 5 {multas_path} #unix

��������������h�E
�= �= �= �= �= �= �O����������������= �= �= �= �= �= �= �= �= �= �= �= �= �|S�������������f6�qE�uJ�uJ�k<�nA�wL�m?�b1�d3�Ƕ����������T�= �= �= �= �= �= �= �= �= �= �= �= ��������v�����k��z��z��w�����������r�������̼��k����rF�ͽ�{Q�= �= �= �= �= �= �= �= �= �= �= �= �����������t�= �= �= �= �?�������D	�������yO�= �¯��������[�= �= �= �= �= �= �= �= �= �= �= �= �����������i�= �= �= �= �?�����w��[��������l�= �����������Z�= �= �= �= �= �= �= �= �= �= �= �= �����������j�= �= �= �= �?����������������R�= �����������Z�= �= �= �= �= �= �= �= �= �= �= �= �����������j�= �= �= �= �?����������������= �= �����������Z�= �= �= �= �= �= �= �= �= �= �= �= �����������j�= �= �= �= �?�������������h9�= �= �����������Z�= �= �= �= �= �= �= �= �= �= �= �= �����������j�= �= �= �= �?����ð�������R�= �= �����������Z�= �= �= �= �= �= �= �= �= �= �= �= ����ǵ�����q�= �= �= �= �?�������ʹ����R�= �= �����������`�= �= �= �= �= �= �= �= �= �= �= �= �����������t�= �= �= �oB�������������Q�= �= �= �������˺��d�= �= �= �= �= �= �= �= �= �= �= �= �����������j�= �>����������������������{Q�= �= �����������Z�= �= �= �= �= �= �= �= �= �= �= �= �����������j�= �xN�������������������������D	�= �����������Z�= �= �= �= �= �= �= �= �= �= �= �= �����������j�= �vK�������������������������C�= �����������Z�= �= �= �= �= �= �= �= �= �= �= �= �����������j�= �= ����������������������uI�= �= �����������Z�= �= �= �= �= �= �= �= �= �= �= �= �����������h�= �= �= �c2�����������h�N�= �= �= �����������Z�= �= �= �= �= �= �= �= �= �= �= �= �������������˺�ξ�ͽ�ų�¯����¯�¯�ɸ�ξ�ξ�˻�����������Z�= �= �= �= �= �= �= �= �= �= �= �= �����w�����������������������m�����������������������\�����e�= �= �= �= �= �= �= �= �= �= �= �= ����������������������������Ƕ����������������������ǵ�����Z�= �= �= �= �= �= �= �= �= �= �= �= �����������������������������������������������������������c�= �= �= �= �= �= �= �= �= �= �= �= �¯�����������������v�ð�����������������������������������}�= �= �= �= �= �= �= �= �= �= �= �= �ƴ�����������������q�ƴ�����������������~�������������������= �= �= �= �= �= �= �= �= �= �= �= ��t�������������������������ƴ�������ȷ����������ǵ�������wL�= �= �= �= �= �= �= �= �= �= �= �= �������������ʹ����Ĳ����Ƕ�������������Ĳ����Ĳ����������{R�= �= �= �= �= �= �= �= �= �= �= �@�������˻�˻��������~���������������������������������ð����= �= �= �= �= �= �= �= �= �= �= �B�����������������������Y��������������n�����������j����������= �= �= �= �= �= �= �= �= �= �= �wL�������A�B�������vK�= �c2����ʹ�L�= ��w�����m�= �R�ų����W"�= �= �= �= �= �= �= �= �= �\)�����[�= �= �= �O�xM�= �= �= �m?�['�= �= �C�}T�@�= �= �A��}��i�\)�= �= �= �=                                                                                                                                 

Con el encoding latin-1 nos ahorramos problemas con caracteres acentuados.

In [18]:
multas_path2="data/201712_multas_circulacion_detalle.csv"
df_multas = pd.read_csv(multas_path2, sep=';', encoding='latin-1')
df_multas.head(20)

,CALIFICACION,LUGAR,MES,ANIO,HORA,IMP_BOL,DESCUENTO,PUNTOS,DENUNCIANTE,HECHO-BOL,VEL_LIMITE,VEL_CIRCULA,COORDENADA_X,COORDENADA_Y
0,LEVE,LUIS DE HOYOS SAINZ FTE 196,12,2017,13.00,90.0,SI,0,POLICIA MUNICIPAL,ESTACIONAR EN LUGAR PROHIBIDO DEBIDAMENTE SEÑA...,,,,
1,LEVE,AEROPUERTO SALIDA T 1,12,2017,12.10,90.0,SI,0,POLICIA MUNICIPAL,ESTACIONAR EN LUGAR PROHIBIDO DEBIDAMENTE SEÑA...,,,,
2,GRAVE,CTRA CANILLAS 2,12,2017,11.30,200.0,SI,0,POLICIA MUNICIPAL,ESTACIONAR EN ZONA SEÑALIZADA PARA USO EXCLUSI...,,,,
3,GRAVE,"M 30 NL KM 13,250 CARRIL 3",12,2017,6.21,500.0,SI,6,POLICIA MUNICIPAL,SOBREPASAR LA VELOCIDADMÁXIMA EN VÍAS LIMITADA...,70,131,,
4,LEVE,CL ORENSE 24,12,2017,17.42,90.0,SI,0,SER,"ESTACIONAR, SIN LA CORRESPONDIENTE AUTORIZACIÓ...",,,,
5,GRAVE,PO GENERAL SAGARDIA RAMOS 16,12,2017,7.08,200.0,SI,0,POLICIA MUNICIPAL,ESTACIONAR OBSTACULIZANDO LA UTILIZACIÓN DE UN...,,,,
6,LEVE,AEROPUERTO SALIDA T 1,12,2017,12.15,90.0,SI,0,POLICIA MUNICIPAL,ESTACIONAR EN LUGAR PROHIBIDO DEBIDAMENTE SEÑA...,,,,
7,GRAVE,CL ORENSE 8,12,2017,18.08,200.0,SI,0,SER,ESTACIONAR EN CARRIL DE CIRCULACION. ...,,,,
8,GRAVE,AV BADAJOZ 10,12,2017,3.45,200.0,SI,0,POLICIA MUNICIPAL,CONDUCCION NEGLIGENTE: CIRCULABA DE DERECHA A ...,,,,
9,GRAVE,VILLABLANCA 29,12,2017,20.21,200.0,SI,0,POLICIA MUNICIPAL,ESTACIONAR EN ZONA SEÑALIZADA PARA USO EXCLUSI...,,,,
10,LEVE,AEROPUERTO LLEGADA T 1,12,2017,17.00,90.0,SI,0,POLICIA MUNICIPAL,ESTACIONAR EN LUGAR PROHIBIDO DEBIDAMENTE SEÑA...,,,,
11,LEVE,AEROPUERTO SALIDA T 1,12,2017,18.16,90.0,SI,0,POLICIA MUNICIPAL,ESTACIONAR EN LUGAR PROHIBIDO DEBIDAMENTE SEÑA...,,,,
12,LEVE,AV BRASIL 1,12,2017,12.47,90.0,SI,0,SER,"ESTACIONAR, SIN LA CORRESPONDIENTE AUTORIZACIÓ...",,,,
13,LEVE,CL ORENSE 16,12,2017,18.58,30.0,SI,0,SER,ESTACIONAR CON AUTORIZACIÓN EN LUGAR HABILITAD...,,,,
14,GRAVE,"M 30 KM 6,700 CALZADA 1",12,2017,5.43,500.0,SI,6,POLICIA MUNICIPAL,SOBREPASAR LA VELOCIDADMÁXIMA EN VÍAS LIMITADA...,90,154,,
15,LEVE,AV BRASIL 2,12,2017,12.50,90.0,SI,0,SER,"ESTACIONAR, SIN LA CORRESPONDIENTE AUTORIZACIÓ...",,,,
16,LEVE,AV BRASIL 1,12,2017,12.55,90.0,SI,0,SER,"ESTACIONAR, SIN LA CORRESPONDIENTE AUTORIZACIÓ...",,,,
17,LEVE,AV GENERAL PERON 27,12,2017,13.06,30.0,SI,0,SER,ESTACIONAR CON AUTORIZACIÓN EN LUGAR HABILITAD...,,,,
18,LEVE,BAILEN FTE 19,12,2017,14.50,60.0,SI,0,POLICIA MUNICIPAL,NO ADVERTIR LA MANIOBRAAL RESTO DE USUARIOS DE...,,,,
19,GRAVE,VILLARDONDIEGO 18,12,2017,17.10,200.0,SI,0,POLICIA MUNICIPAL,ESTACIONAR OBSTACULIZANDO LA UTILIZACIÓN NORMA...,,,,

Strings can be treaky...

In [19]:

df_multas[df_multas['LUGAR'] == ' LUIS DE HOYOS SAINZ FTE 196 ']

Empty DataFrame
Columns: [CALIFICACION, LUGAR, MES, ANIO, HORA, IMP_BOL, DESCUENTO, PUNTOS, DENUNCIANTE, HECHO-BOL, VEL_LIMITE, VEL_CIRCULA, COORDENADA_X, COORDENADA_Y]
Index: []

but with a bit of care...

In [20]:
mi_portal ="LUIS DE HOYOS SAINZ FTE 196".strip()

In [21]:
df_multas[df_multas['LUGAR'].str.strip() == mi_portal]

,CALIFICACION,LUGAR,MES,ANIO,HORA,IMP_BOL,DESCUENTO,PUNTOS,DENUNCIANTE,HECHO-BOL,VEL_LIMITE,VEL_CIRCULA,COORDENADA_X,COORDENADA_Y
0,LEVE,LUIS DE HOYOS SAINZ FTE 196,12,2017,13.0,90.0,SI,0,POLICIA MUNICIPAL,ESTACIONAR EN LUGAR PROHIBIDO DEBIDAMENTE SEÑA...,,,,

We can play with this dataframe... XD

In [22]:
df_multas[df_multas['LUGAR'].str.startswith("ARDEMANS")]

,CALIFICACION,LUGAR,MES,ANIO,HORA,IMP_BOL,DESCUENTO,PUNTOS,DENUNCIANTE,HECHO-BOL,VEL_LIMITE,VEL_CIRCULA,COORDENADA_X,COORDENADA_Y
165643,GRAVE,ARDEMANS 35,12,2017,20.17,200.0,SI,0,AGENTES DE MOVILIDAD,ESTACIONAR OBSTACULIZANDO LA UTILIZACIÓN DE UN...,,,,

In [23]:
df_multas['IMP_BOL'].mean()

104.16942118497181

In [24]:
df_multas['IMP_BOL'].sum()

21335460.0

In [28]:
descuentos = df_multas['DESCUENTO']
descuentos.value_counts()

SI    204814
NO         1
Name: DESCUENTO, dtype: int64

#### Exercise

Calculate the amount that the city hall took in, after discount. Assume that the discount is 50%, for each line that has 'SI' in column 'DESCUENTO'.

In [29]:
total=df_multas['IMP_BOL'].sum()*0.5
total=total+df_multas['IMP_BOL'][df_multas['DESCUENTO']=='NO'].values[0]
total

10668030.0

In [30]:
df_multas['PRUEBA']=df_multas['IMP_BOL']
df_multas['PRUEBA']=df_multas['IMP_BOL'][df_multas['DESCUENTO']=='SI']*0.5
df_multas['PRUEBA'].max()

500.0

In [31]:
df_multas['HECHO-BOL']=df_multas['HECHO-BOL'].str.strip().str.lower()
df_multas['HECHO-BOL'].unique().size

284

In [32]:
df_multas['DESCUENTO_PCT'] = 0.5 *(df_multas['DESCUENTO'] == 'SI')
df_multas['DESCUENTO_PCT'].head()

0    0.5
1    0.5
2    0.5
3    0.5
4    0.5
Name: DESCUENTO_PCT, dtype: float64

In [33]:
df_multas['IMPORTE_FINAL'] = df_multas['IMP_BOL'] * (1 - df_multas['DESCUENTO_PCT'])

#### Let's time it

In [34]:
df_multas = pd.read_csv(multas_path2, sep=';', encoding='latin-1')

In [35]:
df_multas['DESCUENTO_PCT'] = .5 *(df_multas['DESCUENTO'] == 'SI')
df_multas['IMPORTE_FINAL'] = df_multas['IMP_BOL'] * (1 - df_multas['DESCUENTO_PCT'])
df_multas['IMPORTE_FINAL'].sum()

10667880.0

# Saving to Excel

In order to save and read excels, pandas needs addtional modules: xlrd, xlwt and xlsxwriter or openpyxl

In [36]:
df[df['DEPARTURES_PERFORMED'] > 50].to_excel('out.xls')

In [37]:
pd.ExcelWriter?

In [38]:
df[df['DEPARTURES_PERFORMED'] > 50].to_excel('out.xlsx')

# Saving to CSV

In [39]:
df.to_csv('out.csv')

If we don't pass any argument, to_csv will return the contents of the DataFrame, in csv format, as a string.

In [40]:
file_as_string = df.to_csv()

file_as_string[:100]

',DEPARTURES_SCHEDULED,DEPARTURES_PERFORMED,PAYLOAD,SEATS,PASSENGERS,FREIGHT,MAIL,DISTANCE,RAMP_TO_RA'

# To Sql Database

In [41]:
import sqlite3
conn = sqlite3.connect('example.db')

In [42]:
df.to_sql('traffic', conn)

/home/dsc/anaconda3/lib/python3.6/site-packages/pandas/core/generic.py:1534: UserWarning: The spaces in these column names will not be changed. In pandas versions < 0.14, spaces were converted to underscores.
  chunksize=chunksize, dtype=dtype)

ValueError: Table 'traffic' already exists.

# To dictionary and to json

json is the most widely used data interchange format over the web.

In [43]:
!pwd #only for unix

/home/dsc/Repos/MasterDataScience/Class_Master

In [44]:
df[:3].to_dict()

{'AIRCRAFT_CONFIG': {0: 1, 1: 1, 2: 1},
 'AIRCRAFT_GROUP': {0: 6, 1: 6, 2: 6},
 'AIRCRAFT_TYPE': {0: 669, 1: 669, 2: 669},
 'AIRLINE_ID': {0: 21407.0, 1: 21407.0, 2: 21407.0},
 'AIR_TIME': {0: 0.0, 1: 0.0, 2: 0.0},
 'CARRIER': {0: '10Q', 1: '10Q', 2: '10Q'},
 'CARRIER_GROUP': {0: 0, 1: 0, 2: 0},
 'CARRIER_GROUP_NEW': {0: 0.0, 1: 0.0, 2: 0.0},
 'CARRIER_NAME': {0: 'Swiss Air Ambulance',
  1: 'Swiss Air Ambulance',
  2: 'Swiss Air Ambulance'},
 'CLASS': {0: 'L', 1: 'L', 2: 'L'},
 'DATA_SOURCE': {0: 'IF', 1: 'IF', 2: 'DF'},
 'DEPARTURES_PERFORMED': {0: 1.0, 1: 2.0, 2: 1.0},
 'DEPARTURES_SCHEDULED': {0: 0.0, 1: 0.0, 2: 0.0},
 'DEST': {0: 'BSL', 1: 'TEB', 2: 'MFE'},
 'DEST_AIRPORT_ID': {0: 10762, 1: 15167, 2: 13256},
 'DEST_AIRPORT_SEQ_ID': {0: 1076203, 1: 1516702, 2: 1325602},
 'DEST_CITY_MARKET_ID': {0: 30762, 1: 35167, 2: 33256},
 'DEST_CITY_NAME': {0: 'Mulhouse, France',
  1: 'Teterboro, NJ',
  2: 'Mission/McAllen/Edinburg, TX'},
 'DEST_COUNTRY': {0: 'FR', 1: 'US', 2: 'US'},
 'DEST_COUNTRY_NAME': {0: 'France', 1: 'United States', 2: 'United States'},
 'DEST_STATE_ABR': {0: nan, 1: 'NJ', 2: 'TX'},
 'DEST_STATE_FIPS': {0: nan, 1: 34.0, 2: 48.0},
 'DEST_STATE_NM': {0: nan, 1: 'New Jersey', 2: 'Texas'},
 'DEST_WAC': {0: 427, 1: 21, 2: 74},
 'DISTANCE': {0: 3899.0, 1: 2589.0, 2: 1210.0},
 'DISTANCE_GROUP': {0: 8, 1: 6, 2: 3},
 'FREIGHT': {0: 0.0, 1: 0.0, 2: 0.0},
 'MAIL': {0: 0.0, 1: 0.0, 2: 0.0},
 'MONTH': {0: 1, 1: 1, 2: 1},
 'ORIGIN': {0: 'EWR', 1: 'KEF', 2: 'LAS'},
 'ORIGIN_AIRPORT_ID': {0: 11618, 1: 12651, 2: 12889},
 'ORIGIN_AIRPORT_SEQ_ID': {0: 1161802, 1: 1265101, 2: 1288903},
 'ORIGIN_CITY_MARKET_ID': {0: 31703, 1: 32651, 2: 32211},
 'ORIGIN_CITY_NAME': {0: 'Newark, NJ',
  1: 'Keflavik/Reykjavik, Iceland',
  2: 'Las Vegas, NV'},
 'ORIGIN_COUNTRY': {0: 'US', 1: 'IS', 2: 'US'},
 'ORIGIN_COUNTRY_NAME': {0: 'United States', 1: 'Iceland', 2: 'United States'},
 'ORIGIN_STATE_ABR': {0: 'NJ', 1: nan, 2: 'NV'},
 'ORIGIN_STATE_FIPS': {0: 34.0, 1: nan, 2: 32.0},
 'ORIGIN_STATE_NM': {0: 'New Jersey', 1: nan, 2: 'Nevada'},
 'ORIGIN_WAC': {0: 21, 1: 439, 2: 85},
 'PASSENGERS': {0: 2.0, 1: 2.0, 2: 2.0},
 'PAYLOAD': {0: 528.0, 1: 3621.0, 2: 2169.0},
 'QUARTER': {0: 1, 1: 1, 2: 1},
 'RAMP_TO_RAMP': {0: 0.0, 1: 0.0, 2: 0.0},
 'REGION': {0: 'I', 1: 'I', 2: 'I'},
 'SEATS': {0: 11.0, 1: 22.0, 2: 11.0},
 'UNIQUE_CARRIER': {0: '10Q', 1: '10Q', 2: '10Q'},
 'UNIQUE_CARRIER_ENTITY': {0: '71084', 1: '71084', 2: '71084'},
 'UNIQUE_CARRIER_NAME': {0: 'Swiss Air Ambulance',
  1: 'Swiss Air Ambulance',
  2: 'Swiss Air Ambulance'},
 'Unnamed: 50': {0: nan, 1: nan, 2: nan},
 'YEAR': {0: 2015, 1: 2015, 2: 2015}}

In [53]:
df[:3].to_dict(orient='rows')

[{'AIRCRAFT_CONFIG': 1,
  'AIRCRAFT_GROUP': 6,
  'AIRCRAFT_TYPE': 669,
  'AIRLINE_ID': 21407.0,
  'AIR_TIME': 0.0,
  'CARRIER': '10Q',
  'CARRIER_GROUP': 0,
  'CARRIER_GROUP_NEW': 0.0,
  'CARRIER_NAME': 'Swiss Air Ambulance',
  'CLASS': 'L',
  'DATA_SOURCE': 'IF',
  'DEPARTURES_PERFORMED': 1.0,
  'DEPARTURES_SCHEDULED': 0.0,
  'DEST': 'BSL',
  'DEST_AIRPORT_ID': 10762,
  'DEST_AIRPORT_SEQ_ID': 1076203,
  'DEST_CITY_MARKET_ID': 30762,
  'DEST_CITY_NAME': 'Mulhouse, France',
  'DEST_COUNTRY': 'FR',
  'DEST_COUNTRY_NAME': 'France',
  'DEST_STATE_ABR': nan,
  'DEST_STATE_FIPS': nan,
  'DEST_STATE_NM': nan,
  'DEST_WAC': 427,
  'DISTANCE': 3899.0,
  'DISTANCE_GROUP': 8,
  'FREIGHT': 0.0,
  'MAIL': 0.0,
  'MONTH': 1,
  'ORIGIN': 'EWR',
  'ORIGIN_AIRPORT_ID': 11618,
  'ORIGIN_AIRPORT_SEQ_ID': 1161802,
  'ORIGIN_CITY_MARKET_ID': 31703,
  'ORIGIN_CITY_NAME': 'Newark, NJ',
  'ORIGIN_COUNTRY': 'US',
  'ORIGIN_COUNTRY_NAME': 'United States',
  'ORIGIN_STATE_ABR': 'NJ',
  'ORIGIN_STATE_FIPS': 34.0,
  'ORIGIN_STATE_NM': 'New Jersey',
  'ORIGIN_WAC': 21,
  'PASSENGERS': 2.0,
  'PAYLOAD': 528.0,
  'QUARTER': 1,
  'RAMP_TO_RAMP': 0.0,
  'REGION': 'I',
  'SEATS': 11.0,
  'UNIQUE_CARRIER': '10Q',
  'UNIQUE_CARRIER_ENTITY': '71084',
  'UNIQUE_CARRIER_NAME': 'Swiss Air Ambulance',
  'Unnamed: 50': nan,
  'YEAR': 2015},
 {'AIRCRAFT_CONFIG': 1,
  'AIRCRAFT_GROUP': 6,
  'AIRCRAFT_TYPE': 669,
  'AIRLINE_ID': 21407.0,
  'AIR_TIME': 0.0,
  'CARRIER': '10Q',
  'CARRIER_GROUP': 0,
  'CARRIER_GROUP_NEW': 0.0,
  'CARRIER_NAME': 'Swiss Air Ambulance',
  'CLASS': 'L',
  'DATA_SOURCE': 'IF',
  'DEPARTURES_PERFORMED': 2.0,
  'DEPARTURES_SCHEDULED': 0.0,
  'DEST': 'TEB',
  'DEST_AIRPORT_ID': 15167,
  'DEST_AIRPORT_SEQ_ID': 1516702,
  'DEST_CITY_MARKET_ID': 35167,
  'DEST_CITY_NAME': 'Teterboro, NJ',
  'DEST_COUNTRY': 'US',
  'DEST_COUNTRY_NAME': 'United States',
  'DEST_STATE_ABR': 'NJ',
  'DEST_STATE_FIPS': 34.0,
  'DEST_STATE_NM': 'New Jersey',
  'DEST_WAC': 21,
  'DISTANCE': 2589.0,
  'DISTANCE_GROUP': 6,
  'FREIGHT': 0.0,
  'MAIL': 0.0,
  'MONTH': 1,
  'ORIGIN': 'KEF',
  'ORIGIN_AIRPORT_ID': 12651,
  'ORIGIN_AIRPORT_SEQ_ID': 1265101,
  'ORIGIN_CITY_MARKET_ID': 32651,
  'ORIGIN_CITY_NAME': 'Keflavik/Reykjavik, Iceland',
  'ORIGIN_COUNTRY': 'IS',
  'ORIGIN_COUNTRY_NAME': 'Iceland',
  'ORIGIN_STATE_ABR': nan,
  'ORIGIN_STATE_FIPS': nan,
  'ORIGIN_STATE_NM': nan,
  'ORIGIN_WAC': 439,
  'PASSENGERS': 2.0,
  'PAYLOAD': 3621.0,
  'QUARTER': 1,
  'RAMP_TO_RAMP': 0.0,
  'REGION': 'I',
  'SEATS': 22.0,
  'UNIQUE_CARRIER': '10Q',
  'UNIQUE_CARRIER_ENTITY': '71084',
  'UNIQUE_CARRIER_NAME': 'Swiss Air Ambulance',
  'Unnamed: 50': nan,
  'YEAR': 2015},
 {'AIRCRAFT_CONFIG': 1,
  'AIRCRAFT_GROUP': 6,
  'AIRCRAFT_TYPE': 669,
  'AIRLINE_ID': 21407.0,
  'AIR_TIME': 0.0,
  'CARRIER': '10Q',
  'CARRIER_GROUP': 0,
  'CARRIER_GROUP_NEW': 0.0,
  'CARRIER_NAME': 'Swiss Air Ambulance',
  'CLASS': 'L',
  'DATA_SOURCE': 'DF',
  'DEPARTURES_PERFORMED': 1.0,
  'DEPARTURES_SCHEDULED': 0.0,
  'DEST': 'MFE',
  'DEST_AIRPORT_ID': 13256,
  'DEST_AIRPORT_SEQ_ID': 1325602,
  'DEST_CITY_MARKET_ID': 33256,
  'DEST_CITY_NAME': 'Mission/McAllen/Edinburg, TX',
  'DEST_COUNTRY': 'US',
  'DEST_COUNTRY_NAME': 'United States',
  'DEST_STATE_ABR': 'TX',
  'DEST_STATE_FIPS': 48.0,
  'DEST_STATE_NM': 'Texas',
  'DEST_WAC': 74,
  'DISTANCE': 1210.0,
  'DISTANCE_GROUP': 3,
  'FREIGHT': 0.0,
  'MAIL': 0.0,
  'MONTH': 1,
  'ORIGIN': 'LAS',
  'ORIGIN_AIRPORT_ID': 12889,
  'ORIGIN_AIRPORT_SEQ_ID': 1288903,
  'ORIGIN_CITY_MARKET_ID': 32211,
  'ORIGIN_CITY_NAME': 'Las Vegas, NV',
  'ORIGIN_COUNTRY': 'US',
  'ORIGIN_COUNTRY_NAME': 'United States',
  'ORIGIN_STATE_ABR': 'NV',
  'ORIGIN_STATE_FIPS': 32.0,
  'ORIGIN_STATE_NM': 'Nevada',
  'ORIGIN_WAC': 85,
  'PASSENGERS': 2.0,
  'PAYLOAD': 2169.0,
  'QUARTER': 1,
  'RAMP_TO_RAMP': 0.0,
  'REGION': 'I',
  'SEATS': 11.0,
  'UNIQUE_CARRIER': '10Q',
  'UNIQUE_CARRIER_ENTITY': '71084',
  'UNIQUE_CARRIER_NAME': 'Swiss Air Ambulance',
  'Unnamed: 50': nan,
  'YEAR': 2015}]

In [54]:
df[:3].to_json()

'{"DEPARTURES_SCHEDULED":{"0":0.0,"1":0.0,"2":0.0},"DEPARTURES_PERFORMED":{"0":1.0,"1":2.0,"2":1.0},"PAYLOAD":{"0":528.0,"1":3621.0,"2":2169.0},"SEATS":{"0":11.0,"1":22.0,"2":11.0},"PASSENGERS":{"0":2.0,"1":2.0,"2":2.0},"FREIGHT":{"0":0.0,"1":0.0,"2":0.0},"MAIL":{"0":0.0,"1":0.0,"2":0.0},"DISTANCE":{"0":3899.0,"1":2589.0,"2":1210.0},"RAMP_TO_RAMP":{"0":0.0,"1":0.0,"2":0.0},"AIR_TIME":{"0":0.0,"1":0.0,"2":0.0},"UNIQUE_CARRIER":{"0":"10Q","1":"10Q","2":"10Q"},"AIRLINE_ID":{"0":21407.0,"1":21407.0,"2":21407.0},"UNIQUE_CARRIER_NAME":{"0":"Swiss Air Ambulance","1":"Swiss Air Ambulance","2":"Swiss Air Ambulance"},"UNIQUE_CARRIER_ENTITY":{"0":"71084","1":"71084","2":"71084"},"REGION":{"0":"I","1":"I","2":"I"},"CARRIER":{"0":"10Q","1":"10Q","2":"10Q"},"CARRIER_NAME":{"0":"Swiss Air Ambulance","1":"Swiss Air Ambulance","2":"Swiss Air Ambulance"},"CARRIER_GROUP":{"0":0,"1":0,"2":0},"CARRIER_GROUP_NEW":{"0":0.0,"1":0.0,"2":0.0},"ORIGIN_AIRPORT_ID":{"0":11618,"1":12651,"2":12889},"ORIGIN_AIRPORT_SEQ_ID":{"0":1161802,"1":1265101,"2":1288903},"ORIGIN_CITY_MARKET_ID":{"0":31703,"1":32651,"2":32211},"ORIGIN":{"0":"EWR","1":"KEF","2":"LAS"},"ORIGIN_CITY_NAME":{"0":"Newark, NJ","1":"Keflavik\\/Reykjavik, Iceland","2":"Las Vegas, NV"},"ORIGIN_STATE_ABR":{"0":"NJ","1":null,"2":"NV"},"ORIGIN_STATE_FIPS":{"0":34.0,"1":null,"2":32.0},"ORIGIN_STATE_NM":{"0":"New Jersey","1":null,"2":"Nevada"},"ORIGIN_COUNTRY":{"0":"US","1":"IS","2":"US"},"ORIGIN_COUNTRY_NAME":{"0":"United States","1":"Iceland","2":"United States"},"ORIGIN_WAC":{"0":21,"1":439,"2":85},"DEST_AIRPORT_ID":{"0":10762,"1":15167,"2":13256},"DEST_AIRPORT_SEQ_ID":{"0":1076203,"1":1516702,"2":1325602},"DEST_CITY_MARKET_ID":{"0":30762,"1":35167,"2":33256},"DEST":{"0":"BSL","1":"TEB","2":"MFE"},"DEST_CITY_NAME":{"0":"Mulhouse, France","1":"Teterboro, NJ","2":"Mission\\/McAllen\\/Edinburg, TX"},"DEST_STATE_ABR":{"0":null,"1":"NJ","2":"TX"},"DEST_STATE_FIPS":{"0":null,"1":34.0,"2":48.0},"DEST_STATE_NM":{"0":null,"1":"New Jersey","2":"Texas"},"DEST_COUNTRY":{"0":"FR","1":"US","2":"US"},"DEST_COUNTRY_NAME":{"0":"France","1":"United States","2":"United States"},"DEST_WAC":{"0":427,"1":21,"2":74},"AIRCRAFT_GROUP":{"0":6,"1":6,"2":6},"AIRCRAFT_TYPE":{"0":669,"1":669,"2":669},"AIRCRAFT_CONFIG":{"0":1,"1":1,"2":1},"YEAR":{"0":2015,"1":2015,"2":2015},"QUARTER":{"0":1,"1":1,"2":1},"MONTH":{"0":1,"1":1,"2":1},"DISTANCE_GROUP":{"0":8,"1":6,"2":3},"CLASS":{"0":"L","1":"L","2":"L"},"DATA_SOURCE":{"0":"IF","1":"IF","2":"DF"},"Unnamed: 50":{"0":null,"1":null,"2":null}}'

# Reading Excel

In [55]:
df2 = pd.read_excel('out.xls')
df2

,DEPARTURES_SCHEDULED,DEPARTURES_PERFORMED,PAYLOAD,SEATS,PASSENGERS,FREIGHT,MAIL,DISTANCE,RAMP_TO_RAMP,AIR_TIME,...,AIRCRAFT_GROUP,AIRCRAFT_TYPE,AIRCRAFT_CONFIG,YEAR,QUARTER,MONTH,DISTANCE_GROUP,CLASS,DATA_SOURCE,Unnamed: 50
37,0,61,5365411,18353,16933,571685,0,4395,0,0,...,6,627,1,2015,1,1,9,F,IF,NaN
42,0,61,5365411,18353,16827,1274568,0,4395,0,0,...,6,627,1,2015,1,1,9,F,IF,NaN
158,0,51,2706103,17384,13517,0,0,2002,0,0,...,6,627,1,2015,1,1,5,F,IF,NaN
159,0,51,2751949,17384,13746,0,0,2002,0,0,...,6,627,1,2015,1,1,5,F,IF,NaN
181,0,62,9292527,20584,16739,1505486,0,6504,0,0,...,6,637,1,2015,1,1,14,F,IF,NaN
186,0,62,9256991,20584,19123,1847391,0,6504,0,0,...,6,637,1,2015,1,1,14,F,IF,NaN
199,0,184,25907200,0,0,23870728,0,1506,0,0,...,6,696,2,2015,1,1,4,G,IF,NaN
201,0,62,8729600,0,0,7389870,0,1388,0,0,...,6,696,2,2015,1,1,3,G,IF,NaN
205,0,134,18867200,0,0,9486624,0,1506,0,0,...,6,696,2,2015,1,1,4,G,IF,NaN
212,0,59,4517040,17818,14384,309318,0,4661,0,0,...,6,696,1,2015,1,1,10,F,IF,NaN
218,0,59,3829100,17818,16328,82482,0,4661,0,0,...,6,696,1,2015,1,1,10,F,IF,NaN
225,0,51,4039200,14994,11012,392236,0,4095,0,0,...,8,871,1,2015,1,1,9,F,IF,NaN
301,0,584,700800,3254,2379,813,0,11,7673,5921,...,0,79,1,2015,1,1,1,L,DU,NaN
303,0,80,176000,640,570,1214,0,11,1212,972,...,1,194,1,2015,1,1,1,L,DU,NaN
309,0,579,694800,3224,2499,55,0,11,8843,7106,...,0,79,1,2015,1,1,1,L,DU,NaN
310,0,74,162800,592,528,0,0,11,1036,814,...,1,194,1,2015,1,1,1,L,DU,NaN
311,0,81,281756,729,367,4717,5838,56,3093,2445,...,4,415,1,2015,1,1,1,F,DU,NaN
313,0,89,310650,801,434,1326,37247,56,3929,3225,...,4,415,1,2015,1,1,1,F,DU,NaN
318,0,106,137800,530,206,625,8617,16,1488,1276,...,0,35,3,2015,1,1,1,F,DU,NaN
325,0,100,130000,500,191,75,335,16,1401,1201,...,0,35,3,2015,1,1,1,F,DU,NaN
551,0,77,562100,2306,1213,26319,23175,288,6281,5356,...,4,456,1,2015,1,1,1,F,DU,NaN
558,0,64,472050,1908,1256,16863,32765,329,5594,4862,...,4,456,1,2015,1,1,1,F,DU,NaN
560,0,159,1064650,4770,3308,12467,1646,792,29125,27364,...,4,456,1,2015,1,1,2,F,DU,NaN
572,0,59,440450,1935,526,0,0,201,4547,3019,...,4,456,1,2015,1,1,1,F,DU,NaN
573,0,70,522550,2286,675,0,0,333,6741,4820,...,4,456,1,2015,1,1,1,F,DU,NaN
581,0,62,464350,1858,1074,707,9615,329,4876,4360,...,4,456,1,2015,1,1,1,F,DU,NaN
586,0,204,1377900,6120,1215,71372,7150,792,35041,32896,...,4,456,1,2015,1,1,2,F,DU,NaN
590,0,59,440600,1935,483,0,0,201,4140,3021,...,4,456,1,2015,1,1,1,F,DU,NaN
592,0,71,529850,2322,824,0,0,333,7431,5945,...,4,456,1,2015,1,1,1,F,DU,NaN
737,0,53,8076130,18963,14745,887352,0,6799,0,0,...,6,637,1,2015,1,1,14,F,IF,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
146907,521,521,625200,2863,1797,1530,0,11,6537,4974,...,0,79,1,2015,1,1,1,F,DU,NaN
146908,522,522,16314400,63611,51439,98011,0,102,21061,11784,...,6,608,1,2015,1,3,1,F,DU,NaN
146909,525,518,932400,4662,3167,0,0,96,24864,20202,...,1,125,1,2015,1,3,1,F,IU,NaN
146910,525,524,16386600,63537,44702,92078,0,102,21463,11860,...,6,608,1,2015,1,1,1,F,DU,NaN
146911,526,525,16411100,63590,49097,30821,0,102,18853,11227,...,6,608,1,2015,1,1,1,F,DU,NaN
146912,531,531,637200,2976,1863,157,0,11,6669,5076,...,0,79,1,2015,1,2,1,F,DU,NaN
146913,535,534,16690700,64497,53062,57292,0,163,25798,16485,...,6,608,1,2015,1,2,1,F,DU,NaN
146914,538,535,16727800,64735,52773,74516,0,163,24712,15107,...,6,608,1,2015,1,2,1,F,DU,NaN
146915,540,538,16820600,66329,52007,73443,0,163,24487,15770,...,6,608,1,2015,2,4,1,F,DU,NaN
146916,540,540,16886100,66610,49227,82500,0,163,24569,15292,...,6,608,1,2015,2,4,1,F,DU,NaN
146917,563,563,17612200,68584,58241,82918,0,163,25896,16034,...,6,608,1,2015,1,3,1,F,DU,NaN
146918,565,565,17672100,68765,57892,92282,0,163,26134,16973,...,6,608,1,2015,1,3,1,F,DU,NaN
146919,581,580,18142300,70285,51837,82410,0,163,26805,16405,...,6,608,1,2015,1,1,1,F,DU,NaN
146920,586,584,18261300,70702,56704,63820,0,163,27433,17747,...,6,608,1,2015,1,1,1,F,DU,NaN
146921,613,603,10733400,45828,37708,19396,0,129,28945,23735,...,4,482,1,2015,1,2,1,F,DU,NaN
146922,613,605,10769000,45980,37519,11802,0,129,26704,21896,...,4,482,1,2015,1,2,1,F,DU,NaN
146924,668,661,11765800,50236,38845,15019,0,129,32547,26706,...,4,482,1,2015,1,1,1,F,DU,NaN
146925,674,664,11819200,50464,39168,15244,0,129,30158,24722,...,4,482,1,2015,1,1,1,F,DU,NaN
146926,732,731,22832200,89768,67710,149891,0,100,29449,15869,...,6,608,1,2015,2,4,1,F,DU,NaN
146927,732,728,22741700,89409,68857,89972,0,100,27076,16569,...,6,608,1,2015,2,4,1,F,DU,NaN
146928,741,740,23118800,89280,68943,78235,0,100,30119,18038,...,6,608,1,2015,1,2,1,F,DU,NaN
146929,742,741,23148900,89348,68441,130509,0,100,29662,16174,...,6,608,1,2015,1,2,1,F,DU,NaN
146930,743,726,12922800,55176,43652,19569,0,129,34122,27982,...,4,482,1,2015,2,4,1,F,DU,NaN
146931,745,732,13029600,55632,43894,13763,0,129,32712,26813,...,4,482,1,2015,2,4,1,F,DU,NaN
146932,752,727,12940600,55252,44565,17728,0,129,32687,26808,...,4,482,1,2015,1,3,1,F,DU,NaN
146933,753,729,12976200,55404,44718,19043,0,129,34735,28484,...,4,482,1,2015,1,3,1,F,DU,NaN
146934,771,766,23919200,92783,73599,81189,0,100,29043,17873,...,6,608,1,2015,1,3,1,F,DU,NaN
146935,772,772,24101700,93441,72852,142730,0,100,31216,16561,...,6,608,1,2015,1,3,1,F,DU,NaN
146936,820,815,25438100,98355,70117,143209,0,100,32403,17414,...,6,608,1,2015,1,1,1,F,DU,NaN
146937,822,814,25423500,98382,75216,82020,0,100,32035,19536,...,6,608,1,2015,1,1,1,F,DU,NaN

In [45]:
import requests

response = requests.get('http://datos.madrid.es/egob/catalogo/207831-0-accidentes-trafico.xls')
out = open('accidentes.xls', 'wb')
out.write(response.content)
out.close()

In [100]:
accidentes = pd.read_excel('data/01_ ACCIDENTES POR TIPO EN  DISTRITOS.xls')
accidentes

,01. ACCIDENTES POR TIPO EN DISTRITOS,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Indicadores,Nº Accidentes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Año,2009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total
6,DISTRITO_ACCIDENTE,COLISIÓN DOBLE,COLISIÓN MÚLTIPLE,CHOQUE CON OBJETO FIJO,ATROPELLO,VUELCO,CAÍDA MOTOCICLETA,CAÍDA CICLOMOTOR,CAÍDA BICICLETA,CAÍDA VIAJERO BUS,OTRAS CAUSAS,NaN
7,ARGANZUELA,389,54,126,75,9,43,9,4,5,8,722
8,BARAJAS,89,6,53,21,NaN,12,2,1,2,2,188
9,CARABANCHEL,375,44,171,137,8,36,13,6,9,8,807
10,CENTRO,514,55,171,143,NaN,61,12,3,10,12,981
11,CHAMARTIN,494,70,133,92,10,72,22,2,6,7,908
12,CHAMBERI,414,35,87,87,3,51,12,4,4,5,702
13,CIUDAD LINEAL,398,64,124,101,3,57,17,5,4,4,777
14,FUENCARRAL-EL PARDO,321,47,151,78,11,34,16,7,2,8,675
15,HORTALEZA,215,16,109,58,3,29,13,7,4,4,458
16,LATINA,298,40,134,85,7,24,10,2,9,11,620
17,MONCLOA-ARAVACA,340,57,210,71,11,48,8,7,1,13,766
18,MORATALAZ,151,26,59,40,NaN,23,3,2,3,4,311
19,PUENTE DE VALLECAS,367,54,196,122,8,22,14,2,5,11,801
20,RETIRO,369,59,74,51,4,48,10,8,6,6,635
21,SALAMANCA,535,56,122,104,3,107,31,NaN,5,2,965
22,SAN BLAS,301,29,88,66,3,20,10,3,2,5,527
23,TETUAN,338,23,115,101,1,42,15,5,7,8,655
24,USERA,214,24,96,53,1,13,2,1,4,3,411
25,VICALVARO,86,6,39,15,6,9,4,3,2,2,172
26,VILLA DE VALLECAS,142,6,67,36,3,8,4,1,2,3,272
27,VILLAVERDE,148,19,65,46,4,9,4,3,1,8,307
28,Total,6498,790,2390,1582,98,768,231,76,93,134,12660

In [101]:
accidentes.T.isnull().all()

0      True
1      True
2      True
3      True
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
dtype: bool

In [107]:
accidentes.columns=accidentes.loc()[6].values
accidentes=accidentes.set_index(accidentes.columns[0])
accidentes[7:]

,COLISIÓN DOBLE,COLISIÓN MÚLTIPLE,CHOQUE CON OBJETO FIJO,ATROPELLO,VUELCO,CAÍDA MOTOCICLETA,CAÍDA CICLOMOTOR,CAÍDA BICICLETA,CAÍDA VIAJERO BUS,OTRAS CAUSAS,nan
DISTRITO_ACCIDENTE,,,,,,,,,,,
ARGANZUELA,389,54,126,75,9,43,9,4,5,8,722
BARAJAS,89,6,53,21,NaN,12,2,1,2,2,188
CARABANCHEL,375,44,171,137,8,36,13,6,9,8,807
CENTRO,514,55,171,143,NaN,61,12,3,10,12,981
CHAMARTIN,494,70,133,92,10,72,22,2,6,7,908
CHAMBERI,414,35,87,87,3,51,12,4,4,5,702
CIUDAD LINEAL,398,64,124,101,3,57,17,5,4,4,777
FUENCARRAL-EL PARDO,321,47,151,78,11,34,16,7,2,8,675
HORTALEZA,215,16,109,58,3,29,13,7,4,4,458
LATINA,298,40,134,85,7,24,10,2,9,11,620
MONCLOA-ARAVACA,340,57,210,71,11,48,8,7,1,13,766
MORATALAZ,151,26,59,40,NaN,23,3,2,3,4,311
PUENTE DE VALLECAS,367,54,196,122,8,22,14,2,5,11,801
RETIRO,369,59,74,51,4,48,10,8,6,6,635
SALAMANCA,535,56,122,104,3,107,31,NaN,5,2,965
SAN BLAS,301,29,88,66,3,20,10,3,2,5,527
TETUAN,338,23,115,101,1,42,15,5,7,8,655
USERA,214,24,96,53,1,13,2,1,4,3,411
VICALVARO,86,6,39,15,6,9,4,3,2,2,172
VILLA DE VALLECAS,142,6,67,36,3,8,4,1,2,3,272
VILLAVERDE,148,19,65,46,4,9,4,3,1,8,307
Total,6498,790,2390,1582,98,768,231,76,93,134,12660

In [112]:
pd.read_excel?

In [47]:
file_path = 'data/01_ ACCIDENTES POR TIPO EN  DISTRITOS.xls'

accidentes_2010 = pd.read_excel(file_path, 
                                index_col=0, 
                                header=7, 
                                sheet='2010', 
                                skip_footer=1,
                                usecols='A:K')
accidentes_2010

,COLISIÓN DOBLE,COLISIÓN MÚLTIPLE,CHOQUE CON OBJETO FIJO,ATROPELLO,VUELCO,CAÍDA MOTOCICLETA,CAÍDA CICLOMOTOR,CAÍDA BICICLETA,CAÍDA VIAJERO BUS,OTRAS CAUSAS
DISTRITO_ACCIDENTE,,,,,,,,,,
ARGANZUELA,389,54,126,75,9.0,43,9,4.0,5,8
BARAJAS,89,6,53,21,NaN,12,2,1.0,2,2
CARABANCHEL,375,44,171,137,8.0,36,13,6.0,9,8
CENTRO,514,55,171,143,NaN,61,12,3.0,10,12
CHAMARTIN,494,70,133,92,10.0,72,22,2.0,6,7
CHAMBERI,414,35,87,87,3.0,51,12,4.0,4,5
CIUDAD LINEAL,398,64,124,101,3.0,57,17,5.0,4,4
FUENCARRAL-EL PARDO,321,47,151,78,11.0,34,16,7.0,2,8
HORTALEZA,215,16,109,58,3.0,29,13,7.0,4,4
LATINA,298,40,134,85,7.0,24,10,2.0,9,11
MONCLOA-ARAVACA,340,57,210,71,11.0,48,8,7.0,1,13
MORATALAZ,151,26,59,40,NaN,23,3,2.0,3,4
PUENTE DE VALLECAS,367,54,196,122,8.0,22,14,2.0,5,11
RETIRO,369,59,74,51,4.0,48,10,8.0,6,6
SALAMANCA,535,56,122,104,3.0,107,31,NaN,5,2
SAN BLAS,301,29,88,66,3.0,20,10,3.0,2,5
TETUAN,338,23,115,101,1.0,42,15,5.0,7,8
USERA,214,24,96,53,1.0,13,2,1.0,4,3
VICALVARO,86,6,39,15,6.0,9,4,3.0,2,2
VILLA DE VALLECAS,142,6,67,36,3.0,8,4,1.0,2,3
VILLAVERDE,148,19,65,46,4.0,9,4,3.0,1,8

In [176]:
all_accidents = pd.read_excel(file_path, index_col=0, header=7, sheet_name=None)
all_accidents['2009']

,COLISIÓN DOBLE,COLISIÓN MÚLTIPLE,CHOQUE CON OBJETO FIJO,ATROPELLO,VUELCO,CAÍDA MOTOCICLETA,CAÍDA CICLOMOTOR,CAÍDA BICICLETA,CAÍDA VIAJERO BUS,OTRAS CAUSAS,Unnamed: 11
DISTRITO_ACCIDENTE,,,,,,,,,,,
ARGANZUELA,389,54,126,75,9.0,43,9,4.0,5,8,722
BARAJAS,89,6,53,21,NaN,12,2,1.0,2,2,188
CARABANCHEL,375,44,171,137,8.0,36,13,6.0,9,8,807
CENTRO,514,55,171,143,NaN,61,12,3.0,10,12,981
CHAMARTIN,494,70,133,92,10.0,72,22,2.0,6,7,908
CHAMBERI,414,35,87,87,3.0,51,12,4.0,4,5,702
CIUDAD LINEAL,398,64,124,101,3.0,57,17,5.0,4,4,777
FUENCARRAL-EL PARDO,321,47,151,78,11.0,34,16,7.0,2,8,675
HORTALEZA,215,16,109,58,3.0,29,13,7.0,4,4,458
LATINA,298,40,134,85,7.0,24,10,2.0,9,11,620
MONCLOA-ARAVACA,340,57,210,71,11.0,48,8,7.0,1,13,766
MORATALAZ,151,26,59,40,NaN,23,3,2.0,3,4,311
PUENTE DE VALLECAS,367,54,196,122,8.0,22,14,2.0,5,11,801
RETIRO,369,59,74,51,4.0,48,10,8.0,6,6,635
SALAMANCA,535,56,122,104,3.0,107,31,NaN,5,2,965
SAN BLAS,301,29,88,66,3.0,20,10,3.0,2,5,527
TETUAN,338,23,115,101,1.0,42,15,5.0,7,8,655
USERA,214,24,96,53,1.0,13,2,1.0,4,3,411
VICALVARO,86,6,39,15,6.0,9,4,3.0,2,2,172
VILLA DE VALLECAS,142,6,67,36,3.0,8,4,1.0,2,3,272
VILLAVERDE,148,19,65,46,4.0,9,4,3.0,1,8,307
Total,6498,790,2390,1582,98.0,768,231,76.0,93,134,12660

In [177]:
for k, v in all_accidents.items():
    print(v)

                                COLISIÓN DOBLE                            \
DISTRITO_ACCIDENTE
ARGANZUELA                                                           389
BARAJAS                                                               89
CARABANCHEL                                                          375
CENTRO                                                               514
CHAMARTIN                                                            494
CHAMBERI                                                             414
CIUDAD LINEAL                                                        398
FUENCARRAL-EL PARDO                                                  321
HORTALEZA                                                            215
LATINA                                                               298
MONCLOA-ARAVACA                                                      340
MORATALAZ                                                            151
PUENTE DE VALLECAS                                                   367
RETIRO                                                               369
SALAMANCA                                                            535
SAN BLAS                                                             301
TETUAN                                                               338
USERA                                                                214
VICALVARO                                                             86
VILLA DE VALLECAS                                                    142
VILLAVERDE                                                           148
Total                                                               6498

                                COLISIÓN MÚLTIPLE                         \
DISTRITO_ACCIDENTE
ARGANZUELA                                                            54
BARAJAS                                                                6
CARABANCHEL                                                           44
CENTRO                                                                55
CHAMARTIN                                                             70
CHAMBERI                                                              35
CIUDAD LINEAL                                                         64
FUENCARRAL-EL PARDO                                                   47
HORTALEZA                                                             16
LATINA                                                                40
MONCLOA-ARAVACA                                                       57
MORATALAZ                                                             26
PUENTE DE VALLECAS                                                    54
RETIRO                                                                59
SALAMANCA                                                             56
SAN BLAS                                                              29
TETUAN                                                                23
USERA                                                                 24
VICALVARO                                                              6
VILLA DE VALLECAS                                                      6
VILLAVERDE                                                            19
Total                                                                790

                                CHOQUE CON OBJETO FIJO                    \
DISTRITO_ACCIDENTE
ARGANZUELA                                                           126
BARAJAS                                                               53
CARABANCHEL                                                          171
CENTRO                                                               171
CHAMARTIN                                                            133
CHAMBERI                                                              87
CIUDAD LINEAL                                                        124
FUENCARRAL-EL PARDO                                                  151
HORTALEZA                                                            109
LATINA                                                               134
MONCLOA-ARAVACA                                                      210
MORATALAZ                                                             59
PUENTE DE VALLECAS                                                   196
RETIRO                                                                74
SALAMANCA                                                            122
SAN BLAS                                                              88
TETUAN                                                               115
USERA                                                                 96
VICALVARO                                                             39
VILLA DE VALLECAS                                                     67
VILLAVERDE                                                            65
Total                                                               2390

                                ATROPELLO                                 \
DISTRITO_ACCIDENTE
ARGANZUELA                                                            75
BARAJAS                                                               21
CARABANCHEL                                                          137
CENTRO                                                               143
CHAMARTIN                                                             92
CHAMBERI                                                              87
CIUDAD LINEAL                                                        101
FUENCARRAL-EL PARDO                                                   78
HORTALEZA                                                             58
LATINA                                                                85
MONCLOA-ARAVACA                                                       71
MORATALAZ                                                             40
PUENTE DE VALLECAS                                                   122
RETIRO                                                                51
SALAMANCA                                                            104
SAN BLAS                                                              66
TETUAN                                                               101
USERA                                                                 53
VICALVARO                                                             15
VILLA DE VALLECAS                                                     36
VILLAVERDE                                                            46
Total                                                               1582

                                VUELCO                                    \
DISTRITO_ACCIDENTE
ARGANZUELA                                                           9.0
BARAJAS                                                              NaN
CARABANCHEL                                                          8.0
CENTRO                                                               NaN
CHAMARTIN                                                           10.0
CHAMBERI                                                             3.0
CIUDAD LINEAL                                                        3.0
FUENCARRAL-EL PARDO                                                 11.0
HORTALEZA                                                            3.0
LATINA                                                               7.0
MONCLOA-ARAVACA                                                     11.0
MORATALAZ                                                            NaN
PUENTE DE VALLECAS                                                   8.0
RETIRO                                                               4.0
SALAMANCA                                                            3.0
SAN BLAS                                                             3.0
TETUAN                                                               1.0
USERA                                                                1.0
VICALVARO                                                            6.0
VILLA DE VALLECAS                                                    3.0
VILLAVERDE                                                           4.0
Total                                                               98.0

                                CAÍDA MOTOCICLETA                         \
DISTRITO_ACCIDENTE
ARGANZUELA                                                            43
BARAJAS                                                               12
CARABANCHEL                                                           36
CENTRO                                                                61
CHAMARTIN                                                             72
CHAMBERI                                                              51
CIUDAD LINEAL                                                         57
FUENCARRAL-EL PARDO                                                   34
HORTALEZA                                                             29
LATINA                                                                24
MONCLOA-ARAVACA                                                       48
MORATALAZ                                                             23
PUENTE DE VALLECAS                                                    22
RETIRO                                                                48
SALAMANCA                                                            107
SAN BLAS                                                              20
TETUAN                                                                42
USERA                                                                 13
VICALVARO                                                              9
VILLA DE VALLECAS                                                      8
VILLAVERDE                                                             9
Total                                                                768

                                CAÍDA CICLOMOTOR                          \
DISTRITO_ACCIDENTE
ARGANZUELA                                                             9
BARAJAS                                                                2
CARABANCHEL                                                           13
CENTRO                                                                12
CHAMARTIN                                                             22
CHAMBERI                                                              12
CIUDAD LINEAL                                                         17
FUENCARRAL-EL PARDO                                                   16
HORTALEZA                                                             13
LATINA                                                                10
MONCLOA-ARAVACA                                                        8
MORATALAZ                                                              3
PUENTE DE VALLECAS                                                    14
RETIRO                                                                10
SALAMANCA                                                             31
SAN BLAS                                                              10
TETUAN                                                                15
USERA                                                                  2
VICALVARO                                                              4
VILLA DE VALLECAS                                                      4
VILLAVERDE                                                             4
Total                                                                231

                                CAÍDA BICICLETA                           \
DISTRITO_ACCIDENTE
ARGANZUELA                                                           4.0
BARAJAS                                                              1.0
CARABANCHEL                                                          6.0
CENTRO                                                               3.0
CHAMARTIN                                                            2.0
CHAMBERI                                                             4.0
CIUDAD LINEAL                                                        5.0
FUENCARRAL-EL PARDO                                                  7.0
HORTALEZA                                                            7.0
LATINA                                                               2.0
MONCLOA-ARAVACA                                                      7.0
MORATALAZ                                                            2.0
PUENTE DE VALLECAS                                                   2.0
RETIRO                                                               8.0
SALAMANCA                                                            NaN
SAN BLAS                                                             3.0
TETUAN                                                               5.0
USERA                                                                1.0
VICALVARO                                                            3.0
VILLA DE VALLECAS                                                    1.0
VILLAVERDE                                                           3.0
Total                                                               76.0

                                CAÍDA VIAJERO BUS                         \
DISTRITO_ACCIDENTE
ARGANZUELA                                                             5
BARAJAS                                                                2
CARABANCHEL                                                            9
CENTRO                                                                10
CHAMARTIN                                                              6
CHAMBERI                                                               4
CIUDAD LINEAL                                                          4
FUENCARRAL-EL PARDO                                                    2
HORTALEZA                                                              4
LATINA                                                                 9
MONCLOA-ARAVACA                                                        1
MORATALAZ                                                              3
PUENTE DE VALLECAS                                                     5
RETIRO                                                                 6
SALAMANCA                                                              5
SAN BLAS                                                               2
TETUAN                                                                 7
USERA                                                                  4
VICALVARO                                                              2
VILLA DE VALLECAS                                                      2
VILLAVERDE                                                             1
Total                                                                 93

                                OTRAS CAUSAS                              \
DISTRITO_ACCIDENTE
ARGANZUELA                                                             8
BARAJAS                                                                2
CARABANCHEL                                                            8
CENTRO                                                                12
CHAMARTIN                                                              7
CHAMBERI                                                               5
CIUDAD LINEAL                                                          4
FUENCARRAL-EL PARDO                                                    8
HORTALEZA                                                              4
LATINA                                                                11
MONCLOA-ARAVACA                                                       13
MORATALAZ                                                              4
PUENTE DE VALLECAS                                                    11
RETIRO                                                                 6
SALAMANCA                                                              2
SAN BLAS                                                               5
TETUAN                                                                 8
USERA                                                                  3
VICALVARO                                                              2
VILLA DE VALLECAS                                                      3
VILLAVERDE                                                             8
Total                                                                134

                                Unnamed: 11
DISTRITO_ACCIDENTE
ARGANZUELA                              722
BARAJAS                                 188
CARABANCHEL                             807
CENTRO                                  981
CHAMARTIN                               908
CHAMBERI                                702
CIUDAD LINEAL                           777
FUENCARRAL-EL PARDO                     675
HORTALEZA                               458
LATINA                                  620
MONCLOA-ARAVACA                         766
MORATALAZ                               311
PUENTE DE VALLECAS                      801
RETIRO                                  635
SALAMANCA                               965
SAN BLAS                                527
TETUAN                                  655
USERA                                   411
VICALVARO                               172
VILLA DE VALLECAS                       272
VILLAVERDE                              307
Total                                 12660
                                COLISIÓN DOBLE                            \
DISTRITO_ACCIDENTE
ARGANZUELA                                                           403
BARAJAS                                                               62
CARABANCHEL                                                          357
CENTRO                                                               546
CHAMARTIN                                                            460
CHAMBERI                                                             361
CIUDAD LINEAL                                                        404
FUENCARRAL-EL PARDO                                                  294
HORTALEZA                                                            183
LATINA                                                               273
MONCLOA-ARAVACA                                                      350
MORATALAZ                                                            127
PUENTE DE VALLECAS                                                   324
RETIRO                                                               349
SALAMANCA                                                            506
SAN BLAS                                                             274
TETUAN                                                               331
USERA                                                                178
VICALVARO                                                             65
VILLA DE VALLECAS                                                    124
VILLAVERDE                                                           147
Total                                                               6118

                                COLISIÓN MÚLTIPLE                         \
DISTRITO_ACCIDENTE
ARGANZUELA                                                            48
BARAJAS                                                                5

#### Exercise (homework)

Consolidate the excel into one DataFrame: you will need to create a 'YEAR' column. Think how you can iterate through all the DataFrames. Think also where you can take the value of 'YEAR' from.

In [178]:
for year in all_accidents.keys():
    all_accidents[year]['YEAR']=year

In [179]:
df_accidents=all_accidents['2009']
keys=list(all_accidents.keys())
keys.remove('2009')
for i in range(len(keys)):
    df_accidents=df_accidents.append(all_accidents[keys[i]])
df_accidents

,ATROPELLO,CAÍDA BICICLETA,CAÍDA CICLOMOTOR,CAÍDA MOTOCICLETA,CAÍDA VIAJERO BUS,CHOQUE CON OBJETO FIJO,COLISIÓN DOBLE,COLISIÓN MÚLTIPLE,OTRAS CAUSAS,Unnamed: 11,...,98,3,31,8,12,5,3.1,709,CAÍDA VEHÍCULO 3 RUEDAS,Unnamed: 12
ARGANZUELA,75.0,4.0,9.0,43.0,5.0,126.0,389.0,54.0,8.0,722.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
BARAJAS,21.0,1.0,2.0,12.0,2.0,53.0,89.0,6.0,2.0,188.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CARABANCHEL,137.0,6.0,13.0,36.0,9.0,171.0,375.0,44.0,8.0,807.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CENTRO,143.0,3.0,12.0,61.0,10.0,171.0,514.0,55.0,12.0,981.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CHAMARTIN,92.0,2.0,22.0,72.0,6.0,133.0,494.0,70.0,7.0,908.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CHAMBERI,87.0,4.0,12.0,51.0,4.0,87.0,414.0,35.0,5.0,702.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CIUDAD LINEAL,101.0,5.0,17.0,57.0,4.0,124.0,398.0,64.0,4.0,777.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
FUENCARRAL-EL PARDO,78.0,7.0,16.0,34.0,2.0,151.0,321.0,47.0,8.0,675.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
HORTALEZA,58.0,7.0,13.0,29.0,4.0,109.0,215.0,16.0,4.0,458.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LATINA,85.0,2.0,10.0,24.0,9.0,134.0,298.0,40.0,11.0,620.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MONCLOA-ARAVACA,71.0,7.0,8.0,48.0,1.0,210.0,340.0,57.0,13.0,766.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MORATALAZ,40.0,2.0,3.0,23.0,3.0,59.0,151.0,26.0,4.0,311.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PUENTE DE VALLECAS,122.0,2.0,14.0,22.0,5.0,196.0,367.0,54.0,11.0,801.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
RETIRO,51.0,8.0,10.0,48.0,6.0,74.0,369.0,59.0,6.0,635.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SALAMANCA,104.0,NaN,31.0,107.0,5.0,122.0,535.0,56.0,2.0,965.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SAN BLAS,66.0,3.0,10.0,20.0,2.0,88.0,301.0,29.0,5.0,527.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TETUAN,101.0,5.0,15.0,42.0,7.0,115.0,338.0,23.0,8.0,655.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
USERA,53.0,1.0,2.0,13.0,4.0,96.0,214.0,24.0,3.0,411.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
VICALVARO,15.0,3.0,4.0,9.0,2.0,39.0,86.0,6.0,2.0,172.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
VILLA DE VALLECAS,36.0,1.0,4.0,8.0,2.0,67.0,142.0,6.0,3.0,272.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
VILLAVERDE,46.0,3.0,4.0,9.0,1.0,65.0,148.0,19.0,8.0,307.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Total,1582.0,76.0,231.0,768.0,93.0,2390.0,6498.0,790.0,134.0,12660.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ARGANZUELA,75.0,2.0,15.0,26.0,5.0,103.0,403.0,48.0,6.0,690.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
BARAJAS,22.0,NaN,NaN,11.0,NaN,34.0,62.0,5.0,NaN,135.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CARABANCHEL,114.0,6.0,14.0,22.0,7.0,133.0,357.0,35.0,1.0,696.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CENTRO,169.0,9.0,14.0,60.0,13.0,142.0,546.0,43.0,9.0,1007.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CHAMARTIN,85.0,1.0,16.0,77.0,8.0,128.0,460.0,67.0,5.0,858.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CHAMBERI,103.0,5.0,14.0,66.0,2.0,86.0,361.0,34.0,4.0,676.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CIUDAD LINEAL,90.0,6.0,12.0,39.0,7.0,120.0,404.0,79.0,2.0,767.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
FUENCARRAL-EL PARDO,72.0,6.0,9.0,26.0,3.0,165.0,294.0,49.0,2.0,636.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
SALAMANCA,82.0,13.0,10.0,96.0,11.0,117.0,447.0,66.0,3.0,849.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SAN BLAS,65.0,7.0,9.0,27.0,4.0,69.0,283.0,24.0,4.0,495.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TETUAN,87.0,6.0,19.0,67.0,3.0,71.0,355.0,21.0,6.0,636.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
USERA,65.0,3.0,3.0,15.0,5.0,67.0,199.0,27.0,NaN,387.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
VICALVARO,17.0,4.0,1.0,13.0,NaN,28.0,77.0,7.0,1.0,151.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
VILLA DE VALLECAS,39.0,6.0,4.0,16.0,NaN,52.0,129.0,5.0,2.0,255.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
VILLAVERDE,57.0,4.0,4.0,7.0,3.0,61.0,146.0,12.0,2.0,298.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Total,1525.0,239.0,166.0,983.0,85.0,1804.0,6121.0,736.0,63.0,11782.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ARGANZUELA,57.0,10.0,12.0,46.0,6.0,86.0,328.0,62.0,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,610.0
BARAJAS,34.0,4.0,2.0,12.0,2.0,50.0,95.0,6.0,4.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,213.0
CARABANCHEL,106.0,7.0,18.0,53.0,8.0,121.0,346.0,55.0,6.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,725.0
CENTRO,144.0,33.0,11.0,97.0,5.0,172.0,444.0,23.0,3.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,932.0
CHAMARTIN,80.0,8.0,14.0,105.0,5.0,122.0,499.0,59.0,7.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,904.0
CHAMBERI,88.0,19.0,10.0,63.0,1.0,53.0,382.0,26.0,5.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,647.0
CIUDAD LINEAL,85.0,8.0,15.0,75.0,5.0,119.0,411.0,57.0,8.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,787.0
FUENCARRAL-EL PARDO,70.0,28.0,18.0,56.0,3.0,132.0,345.0,30.0,4.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,692.0
HORTALEZA,56.0,10.0,9.0,33.0,1.0,90.0,248.0,19.0,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,472.0
LATINA,104.0,11.0,12.0,36.0,7.0,119.0,288.0,40.0,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,622.0
MONCLOA-ARAVACA,54.0,27.0,8.0,68.0,2.0,182.0,294.0,61.0,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,709.0
MORATALAZ,32.0,2.0,5.0,23.0,4.0,53.0,150.0,31.0,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,307.0
PUENTE DE VALLECAS,118.0,11.0,11.0,41.0,10.0,140.0,386.0,81.0,5.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,811.0
RETIRO,56.0,33.0,9.0,67.0,1.0,63.0,344.0,69.0,3.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,647.0
SALAMANCA,112.0,22.0,14.0,142.0,14.0,111.0,467.0,65.0,3.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,951.0
SAN BLAS,68.0,9.0,6.0,34.0,5.0,57.0,299.0,20.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,501.0
TETUAN,91.0,13.0,25.0,73.0,5.0,70.0,330.0,43.0,3.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,653.0
USERA,75.0,5.0,2.0,16.0,4.0,74.0,206.0,27.0,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,412.0
VICALVARO,22.0,3.0,2.0,15.0,2.0,38.0,70.0,4.0,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,161.0
VILLA DE VALLECAS,54.0,4.0,4.0,26.0,1.0,42.0,149.0,7.0,3.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,295.0
VILLAVERDE,54.0,6.0,5.0,8.0,2.0,71.0,177.0,11.0,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,336.0
Total,1560.0,273.0,212.0,1089.0,93.0,1965.0,6258.0,796.0,65.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,12387.0

# Reading mysql database

In [61]:
pd.read_sql_query('SELECT * FROM traffic WHERE SEATS > 160', conn)

,index,DEPARTURES_SCHEDULED,DEPARTURES_PERFORMED,PAYLOAD,SEATS,PASSENGERS,FREIGHT,MAIL,DISTANCE,RAMP_TO_RAMP,...,AIRCRAFT_GROUP,AIRCRAFT_TYPE,AIRCRAFT_CONFIG,YEAR,QUARTER,MONTH,DISTANCE_GROUP,CLASS,DATA_SOURCE,Unnamed: 50
0,14,0.0,9.0,562962.0,2548.0,2154.0,0.0,0.0,2188.0,0.0,...,6,696,1,2015,1,1,5,F,IF,None
1,15,0.0,18.0,1237995.0,5159.0,4905.0,0.0,0.0,1873.0,0.0,...,6,696,1,2015,1,1,4,F,IF,None
2,16,0.0,9.0,565173.0,2595.0,2156.0,0.0,0.0,2188.0,0.0,...,6,696,1,2015,1,1,5,F,IF,None
3,17,0.0,18.0,1237436.0,5109.0,4855.0,0.0,0.0,1873.0,0.0,...,6,696,1,2015,1,1,4,F,IF,None
4,18,0.0,4.0,404800.0,1260.0,558.0,0.0,0.0,5713.0,0.0,...,6,696,1,2015,1,1,12,F,IF,None
5,19,0.0,9.0,910800.0,2835.0,1666.0,2882.0,0.0,4879.0,0.0,...,6,696,1,2015,1,1,10,F,IF,None
6,20,0.0,4.0,404800.0,1260.0,833.0,0.0,0.0,5713.0,0.0,...,6,696,1,2015,1,1,12,F,IF,None
7,21,0.0,9.0,910800.0,2835.0,1758.0,39954.0,0.0,4879.0,0.0,...,6,696,1,2015,1,1,10,F,IF,None
8,22,0.0,23.0,2345933.0,6793.0,4946.0,454689.0,0.0,3749.0,0.0,...,6,696,1,2015,1,1,8,F,IF,None
9,23,0.0,29.0,2557427.0,8525.0,7094.0,621786.0,0.0,4733.0,0.0,...,6,696,1,2015,1,1,10,F,IF,None
10,24,0.0,12.0,1049765.0,3569.0,2435.0,224246.0,0.0,4757.0,0.0,...,6,696,1,2015,1,1,10,F,IF,None
11,25,0.0,23.0,2401058.0,6793.0,5503.0,647284.0,0.0,3749.0,0.0,...,6,696,1,2015,1,1,8,F,IF,None
12,26,0.0,21.0,2199395.0,6180.0,4683.0,573408.0,0.0,3968.0,0.0,...,6,696,1,2015,1,1,8,F,IF,None
13,27,0.0,29.0,3020211.0,8530.0,7791.0,455231.0,0.0,4733.0,0.0,...,6,696,1,2015,1,1,10,F,IF,None
14,28,0.0,22.0,2294431.0,6480.0,5596.0,507333.0,0.0,4974.0,0.0,...,6,696,1,2015,1,1,10,F,IF,None
15,29,0.0,14.0,1466137.0,4130.0,2468.0,249731.0,0.0,4413.0,0.0,...,6,696,1,2015,1,1,9,F,IF,None
16,30,0.0,12.0,1250181.0,3569.0,2770.0,102414.0,0.0,4757.0,0.0,...,6,696,1,2015,1,1,10,F,IF,None
17,31,0.0,21.0,2146910.0,6180.0,4639.0,430676.0,0.0,3968.0,0.0,...,6,696,1,2015,1,1,8,F,IF,None
18,32,0.0,22.0,1924391.0,6485.0,5006.0,286066.0,0.0,4974.0,0.0,...,6,696,1,2015,1,1,10,F,IF,None
19,33,0.0,14.0,1435498.0,4130.0,2791.0,310264.0,0.0,4413.0,0.0,...,6,696,1,2015,1,1,9,F,IF,None
20,37,0.0,61.0,5365411.0,18353.0,16933.0,571685.0,0.0,4395.0,0.0,...,6,627,1,2015,1,1,9,F,IF,None
21,40,0.0,27.0,2251555.0,7074.0,5876.0,435222.0,0.0,3449.0,0.0,...,6,627,1,2015,1,1,7,F,IF,None
22,41,0.0,2.0,225601.0,606.0,495.0,17604.0,0.0,3449.0,0.0,...,6,637,1,2015,1,1,7,F,IF,None
23,42,0.0,61.0,5365411.0,18353.0,16827.0,1274568.0,0.0,4395.0,0.0,...,6,627,1,2015,1,1,9,F,IF,None
24,43,0.0,28.0,2333124.0,7321.0,6217.0,501391.0,0.0,3449.0,0.0,...,6,627,1,2015,1,1,7,F,IF,None
25,44,0.0,2.0,225601.0,606.0,573.0,73366.0,0.0,3449.0,0.0,...,6,637,1,2015,1,1,7,F,IF,None
26,45,0.0,1.0,83875.0,275.0,264.0,7383.0,0.0,3937.0,0.0,...,8,873,1,2015,1,1,8,F,IF,None
27,46,0.0,2.0,138283.0,416.0,391.0,27720.0,0.0,3962.0,0.0,...,6,696,1,2015,1,1,8,F,IF,None
28,47,0.0,20.0,1677500.0,5500.0,4838.0,365198.0,0.0,3962.0,0.0,...,8,873,1,2015,1,1,8,F,IF,None
29,48,0.0,5.0,407847.0,1235.0,1089.0,95256.0,0.0,3861.0,0.0,...,6,627,1,2015,1,1,8,F,IF,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90109,146908,522.0,522.0,16314400.0,63611.0,51439.0,98011.0,0.0,102.0,21061.0,...,6,608,1,2015,1,3,1,F,DU,None
90110,146909,525.0,518.0,932400.0,4662.0,3167.0,0.0,0.0,96.0,24864.0,...,1,125,1,2015,1,3,1,F,IU,None
90111,146910,525.0,524.0,16386600.0,63537.0,44702.0,92078.0,0.0,102.0,21463.0,...,6,608,1,2015,1,1,1,F,DU,None
90112,146911,526.0,525.0,16411100.0,63590.0,49097.0,30821.0,0.0,102.0,18853.0,...,6,608,1,2015,1,1,1,F,DU,None
90113,146912,531.0,531.0,637200.0,2976.0,1863.0,157.0,0.0,11.0,6669.0,...,0,79,1,2015,1,2,1,F,DU,None
90114,146913,535.0,534.0,16690700.0,64497.0,53062.0,57292.0,0.0,163.0,25798.0,...,6,608,1,2015,1,2,1,F,DU,None
90115,146914,538.0,535.0,16727800.0,64735.0,52773.0,74516.0,0.0,163.0,24712.0,...,6,608,1,2015,1,2,1,F,DU,None
90116,146915,540.0,538.0,16820600.0,66329.0,52007.0,73443.0,0.0,163.0,24487.0,...,6,608,1,2015,2,4,1,F,DU,None
90117,146916,540.0,540.0,16886100.0,66610.0,49227.0,82500.0,0.0,163.0,24569.0,...,6,608,1,2015,2,4,1,F,DU,None
90118,146917,563.0,563.0,17612200.0,68584.0,58241.0,82918.0,0.0,163.0,25896.0,...,6,608,1,2015,1,3,1,F,DU,None
90119,146918,565.0,565.0,17672100.0,68765.0,57892.0,92282.0,0.0,163.0,26134.0,...,6,608,1,2015,1,3,1,F,DU,None
90120,146919,581.0,580.0,18142300.0,70285.0,51837.0,82410.0,0.0,163.0,26805.0,...,6,608,1,2015,1,1,1,F,DU,None
90121,146920,586.0,584.0,18261300.0,70702.0,56704.0,63820.0,0.0,163.0,27433.0,...,6,608,1,2015,1,1,1,F,DU,None
90122,146921,613.0,603.0,10733400.0,45828.0,37708.0,19396.0,0.0,129.0,28945.0,...,4,482,1,2015,1,2,1,F,DU,None
90123,146922,613.0,605.0,10769000.0,45980.0,37519.0,11802.0,0.0,129.0,26704.0,...,4,482,1,2015,1,2,1,F,DU,None
90124,146923,648.0,23.0,4907970.0,439.0,0.0,1094446.0,151.0,330.0,1506.0,...,6,625,2,2015,1,3,1,G,DU,None
90125,146924,668.0,661.0,11765800.0,50236.0,38845.0,15019.0,0.0,129.0,32547.0,...,4,482,1,2015,1,1,1,F,DU,None
90126,146925,674.0,664.0,11819200.0,50464.0,39168.0,15244.0,0.0,129.0,30158.0,...,4,482,1,2015,1,1,1,F,DU,None
90127,146926,732.0,731.0,22832200.0,89768.0,67710.0,149891.0,0.0,100.0,29449.0,...,6,608,1,2015,2,4,1,F,DU,None
90128,146927,732.0,728.0,22741700.0,89409.0,68857.0,89972.0,0.0,100.0,27076.0,...,6,608,1,2015,2,4,1,F,DU,None
90129,146928,741.0,740.0,23118800.0,89280.0,68943.0,78235.0,0.0,100.0,30119.0,...,6,608,1,2015,1,2,1,F,DU,None
90130,146929,742.0,741.0,23148900.0,89348.0,68441.0,130509.0,0.0,100.0,29662.0,...,6,608,1,2015,1,2,1,F,DU,None
90131,146930,743.0,726.0,12922800.0,55176.0,43652.0,19569.0,0.0,129.0,34122.0,...,4,482,1,2015,2,4,1,F,DU,None
90132,146931,745.0,732.0,13029600.0,55632.0,43894.0,13763.0,0.0,129.0,32712.0,...,4,482,1,2015,2,4,1,F,DU,None
90133,146932,752.0,727.0,12940600.0,55252.0,44565.0,17728.0,0.0,129.0,32687.0,...,4,482,1,2015,1,3,1,F,DU,None
90134,146933,753.0,729.0,12976200.0,55404.0,44718.0,19043.0,0.0,129.0,34735.0,...,4,482,1,2015,1,3,1,F,DU,None
90135,146934,771.0,766.0,23919200.0,92783.0,73599.0,81189.0,0.0,100.0,29043.0,...,6,608,1,2015,1,3,1,F,DU,None
90136,146935,772.0,772.0,24101700.0,93441.0,72852.0,142730.0,0.0,100.0,31216.0,...,6,608,1,2015,1,3,1,F,DU,None
90137,146936,820.0,815.0,25438100.0,98355.0,70117.0,143209.0,0.0,100.0,32403.0,...,6,608,1,2015,1,1,1,F,DU,None
90138,146937,822.0,814.0,25423500.0,98382.0,75216.0,82020.0,0.0,100.0,32035.0,...,6,608,1,2015,1,1,1,F,DU,None